-- Дополнительное задание 
-- 1. Добавила функциональный индекс для процедуры get_driver_salary - со временем данных появится очень много и будет тяжело искать информацию по месяцу и году по всем водителям
CREATE INDEX ix_extract_booking_time_create_year ON booking (extract(YEAR FROM time_create));
CREATE INDEX ix_extract_booking_time_create_month ON booking (extract(MONTH FROM time_create));

-- 2. Добавила индексы на все форейны, по ним часто будут производить поиск
CREATE INDEX ix_BOOKING_BOOKING_STATUS_ID ON BOOKING (BOOKING_STATUS_ID);
CREATE INDEX ix_RATING_PASSENGER2DRIVER_BOOKING_ID ON RATING_PASSENGER2DRIVER (BOOKING_ID);
CREATE INDEX ix_WAY_BOOKING_ID ON WAY (BOOKING_ID);
CREATE INDEX ix_RATING_DRIVER2PASSENGER_BOOKING_ID ON RATING_DRIVER2PASSENGER (BOOKING_ID);
CREATE INDEX ix_RATING_PASSENGER2DRIVER_PASSENGER_ID ON RATING_PASSENGER2DRIVER (PASSENGER_ID);
CREATE INDEX ix_BOOKING_PASSENGER_ID ON BOOKING (PASSENGER_ID);
CREATE INDEX ix_RATING_DRIVER2PASSENGER_PASSENGER_ID ON RATING_DRIVER2PASSENGER (PASSENGER_ID);
CREATE INDEX ix_CURRENCY2COUNTRY_CURRENCY_ID ON CURRENCY2COUNTRY (CURRENCY_ID);
CREATE INDEX ix_RATE_CURRENCY1_ID ON RATE (CURRENCY1_ID);
CREATE INDEX ix_RATE_CURRENCY2_ID ON RATE (CURRENCY2_ID);
CREATE INDEX ix_PAYMENT_CURRENCY_ID ON PAYMENT (CURRENCY_ID);
CREATE INDEX ix_PAYMENT_PAYMENT_TYPE_ID ON PAYMENT (PAYMENT_TYPE_ID);
CREATE INDEX ix_BOOKING_PAYMENT_ID ON BOOKING (PAYMENT_ID);
CREATE INDEX ix_REFUELING_PAYMENT_ID ON REFUELING (PAYMENT_ID);
CREATE INDEX ix_RATING_PASSENGER2DRIVER_DRIVER_ID ON RATING_PASSENGER2DRIVER (DRIVER_ID);
CREATE INDEX ix_BOOKING_DRIVER_ID ON BOOKING (DRIVER_ID);
CREATE INDEX ix_RATING_DRIVER2PASSENGER_DRIVER_ID ON RATING_DRIVER2PASSENGER (DRIVER_ID);
CREATE INDEX ix_REFUELING_DRIVER_ID ON REFUELING (DRIVER_ID);
CREATE INDEX ix_RENT_DRIVER_ID ON RENT (DRIVER_ID);
CREATE INDEX ix_CAR_PARKING_ID ON CAR (PARKING_ID);
CREATE INDEX ix_CAR_CAR_COLOR_ID ON CAR (CAR_COLOR_ID);
CREATE INDEX ix_REFUELING_CAR_ID ON REFUELING (CAR_ID);
CREATE INDEX ix_RENT_CAR_ID ON RENT (CAR_ID);
CREATE INDEX ix_ADDRESS_STREET_ID ON ADDRESS (STREET_ID);
CREATE INDEX ix_STREET_CITY_ID ON STREET (CITY_ID);
CREATE INDEX ix_CITY_COUNTRY_ID ON CITY (COUNTRY_ID);

-- 3. Добавила секционирование на таблицы при создании
-- Таблица booking по дате
-- Таблица rating_driver2passenger по дате
-- Таблица rating_passenger2driver по дате
-- Таблица way по дате
-- Таблица rate по дате
